### ISSUE TITLE
EXC_RESOURCE -> PacketTunnel[7988] exceeded mem limit: ActiveHard 15 MB (fatal)

### ISSUE THREAD

**Issue by 86speed** [mzz2017/shadowsocksR#14]
使用Instruments检查是没有内存泄漏的，但ios使用uutest.cn测速（软件下载地址:uuspeed.uutest.cn），测试到上传速度的时候，会被系统kill掉，提示内存超过15MB
EXC_RESOURCE -> PacketTunnel[7988] exceeded mem limit: ActiveHard 15 MB (fatal)
 
![image](https://user-images.githubusercontent.com/67633762/94646910-ea9e9e80-0321-11eb-9b8c-43f940c7d3af.png)

**Comment by mzz2017** [comment]
ios对内存要求十分苛刻，项目没有对内存进行优化，欢迎提交pr

**Comment by 86speed** [comment]
> 
感觉是 缓存区buffer，没有及时释放导致触发了ios系统15MB限制。
是不是可以把ssrbuffer缓存circular buffer

**Comment by 86speed** [comment]
> ios对内存要求十分苛刻，项目没有对内存进行优化，欢迎提交pr

感觉是 缓存区buffer，没有及时释放导致触发了ios系统15MB限制。
是不是可以把ssrbuffer缓存circular buffer

**Comment by 86speed** [comment]
@mzz2017  有没思路？
libuv、tun2socks-iOS、ssrbuffer.c
不确定从哪块入手、对c不熟
