### ISSUE TITLE
小白提问

### ISSUE THREAD

**Issue by humorwang** [mzz2017/shadowsocksR#15]
请问，这个只是一个客户端对吗？有没有现在比较推荐的服务端项目推荐啊，我想自己搭一个后端没找到合适go后端服务，只有python的不太会玩。

**Comment by mzz2017** [comment]
是的，只有客户端。
SSR很复杂而且被淘汰了，建议参考go-shadowsocks2，而不是SSR。

**Comment by humorwang** [comment]
好的，多谢您的回复。我去看一下这个项目。

**Comment by mzz2017** [comment]
https://github.com/shadowsocks/go-shadowsocks2
