### ISSUE TITLE
建议Client在返回错误的时候不要直接print log

### ISSUE THREAD

**Issue by horsley** [mzz2017/shadowsocksR#16]
考虑传入logger、debug开关等，而非直接使用log包default logger，可以让caller的log console更加干净

https://github.com/v2rayA/shadowsocksR/blob/b52844f2a60f3729860742a8b19bdb40a2463495/client/ssr.go#L37

https://github.com/v2rayA/shadowsocksR/blob/b52844f2a60f3729860742a8b19bdb40a2463495/client/ssr.go#L87

https://github.com/v2rayA/shadowsocksR/blob/b52844f2a60f3729860742a8b19bdb40a2463495/client/ssr.go#L135

**Comment by mzz2017** [comment]
不好意思才看到您的issue，您提了一个非常好的建议，欢迎您的PR，谢谢

**Comment by mzz2017** [comment]
已更改于 https://github.com/v2rayA/shadowsocksR/commit/67597f426517526d08e4809b5d4896d5f756d121
