### ISSUE TITLE
aes-128-ctr + auth_aes128_md5 + tls1.2_ticket_auth 超时

### ISSUE THREAD

**Issue by horsley** [mzz2017/shadowsocksR#4]
method:aes-128-ctr
protocol:auth_aes128_md5
protocol_param: 有
obfs:tls1.2_ticket_auth
obfs_param: 空

这个组合跑example get任意地址都出现超时现象，客户端软件正常，先挂一个issue得空排查一下

**Comment by mzz2017** [comment]
这里chacha20 + auth_aes128_md5 + tls1.2_ticket_auth，双param，正常


mzz2017
m@mzz.pub




------------------ 原始邮件 ------------------
发件人: Horsley Lee <notifications@github.com&gt;
发送时间: 2020年5月15日 13:40
收件人: mzz2017/shadowsocksR <shadowsocksR@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[mzz2017/shadowsocksR] aes-128-ctr + auth_aes128_md5 + tls1.2_ticket_auth 超时 (#4)





 
method:aes-128-ctr
 protocol:auth_aes128_md5
 protocol_param: 有
 obfs:tls1.2_ticket_auth
 obfs_param: 空
 
这个组合跑example get任意地址都出现超时现象，客户端软件正常，先挂一个issue得空排查一下

**Comment by horsley** [comment]
chacha20 + auth_aes128_md5 + tls1.2_ticket_auth 单protocol_param  EOF

**Comment by mzz2017** [comment]
我这里测试通过

**Comment by horsley** [comment]
我这边用到了单端口多用户，不知道是否有影响，我试了avege里面最新的代码也有同样问题

**Comment by mzz2017** [comment]
不清楚，我这边连的是机场，v2rayA的用户没反应过无法连接，这个库是avege的bug修复版，avege有问题是正常的。你可以看看mzz2017/v2rayA是否可以连接你的节点。


mzz2017
m@mzz.pub




------------------ 原始邮件 ------------------
发件人: Horsley Lee <notifications@github.com&gt;
发送时间: 2020年5月15日 18:50
收件人: mzz2017/shadowsocksR <shadowsocksR@noreply.github.com&gt;
抄送: mzz <m@mzz.pub&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[mzz2017/shadowsocksR] aes-128-ctr + auth_aes128_md5 + tls1.2_ticket_auth 超时 (#4)

**Comment by mzz2017** [comment]
测试时请确保当前没有开启透明代理

**Comment by missdeer** [comment]
> 
> 
> 我这边用到了单端口多用户，不知道是否有影响，我试了avege里面最新的代码也有同样问题

avege的单端口多用户基本不能用，也没兴趣继续搞了

**Comment by mzz2017** [comment]
@missdeer 请问之前有定位到相关代码吗

**Comment by missdeer** [comment]
> @missdeer 请问之前有定位到相关代码吗

没有，放弃了。记得当时小数据量时正常，稍微大点就出错
